FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --without dev --no-interaction

EXPOSE 8501
CMD ["poetry", "run", "streamlit", "run", "src/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]