services:
  fastapi:
    image: fplagent-fastapi
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Add this line
  streamlit:
    image: fplagent-streamlit
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"